/*
 * Copyright 2026 Tom Clabault. GNU GPL3 license.
 * GNU GPL3 license copy: https://www.gnu.org/licenses/gpl-3.0.txt
 */

#ifndef HOST_DEVICE_COMMON_MLP_TRAINING_TEST_OPTIONS_H
#define HOST_DEVICE_COMMON_MLP_TRAINING_TEST_OPTIONS_H

#define MLP_TRAINING_TEST_INPUT_SIZE_RAW					 2
#define MLP_TRAINING_TEST_FREQUENCY_ENCODING_NUM_FREQUENCIES 8
#define MLP_TRAINING_TEST_HIDDEN_LAYER_COUNT				 3
#define MLP_TRAINING_TEST_HIDDEN_LAYER_SIZE					 64
#define MLP_TRAINING_TEST_OUTPUT_SIZE						 3
#define MLP_TRAINING_TEST_THREAD_BLOCK_SIZE					 64
#define MLP_TRAINING_TEST_USE_BIASES						 1

#endif
