/*
 * Copyright 2025 Tom Clabault. GNU GPL3 license.
 * GNU GPL3 license copy: https://www.gnu.org/licenses/gpl-3.0.txt
 */

#ifndef HOST_DEVICE_COMMON_RESTIR_COMMON_OPTIONS_H
#define HOST_DEVICE_COMMON_RESTIR_COMMON_OPTIONS_H

#define RESTIR_MIS_WEIGHTS_TYPE_1_OVER_M			   0
#define RESTIR_MIS_WEIGHTS_TYPE_1_OVER_Z			   1
#define RESTIR_MIS_WEIGHTS_TYPE_MIS_LIKE			   2
#define RESTIR_MIS_WEIGHTS_TYPE_MIS_GBH				   3
#define RESTIR_MIS_WEIGHTS_TYPE_PAIRWISE_MIS		   4
#define RESTIR_MIS_WEIGHTS_TYPE_PAIRWISE_MIS_DEFENSIVE 5
#define RESTIR_MIS_WEIGHTS_TYPE_SYMMETRIC_RATIO		   6
#define RESTIR_MIS_WEIGHTS_TYPE_ASYMMETRIC_RATIO	   7

#define ReSTIR_VARIANT_DI 0
#define ReSTIR_VARIANT_GI 1
#define ReSTIR_VARIANT_PT 2

#define ReSTIR_SpatialDirectionalReuseBitCount 64

#endif
