/*
 * Copyright 2026 Tom Clabault. GNU GPL3 license.
 * GNU GPL3 license copy: https://www.gnu.org/licenses/gpl-3.0.txt
 */

#ifndef DEVICE_INCLUDES_ILLUMINATION_AWARE_KD_TREE_ILLUMINATION_AWARE_KD_TREE_SUBDIVISION_MODE_H
#define DEVICE_INCLUDES_ILLUMINATION_AWARE_KD_TREE_ILLUMINATION_AWARE_KD_TREE_SUBDIVISION_MODE_H

enum class IlluminationAwareKDTreeSubdivisionMode
{
	RECORD_SAMPLES_ONLY = 0,
	MEAN_RADIANCE_ONLY	= 1,
	MEAN_DIRECTION_ONLY = 2,
	FULL_MODEL			= 3
};

#endif
