/*
 * Copyright 2024 Tom Clabault. GNU GPL3 license.
 * GNU GPL3 license copy: https://www.gnu.org/licenses/gpl-3.0.txt
 */


#ifndef IMGUI_RENDERER_PERFORMANCE_PRESET_H
#define IMGUI_RENDERER_PERFORMANCE_PRESET_H

enum ImGuiRendererSettingsPreset
{
    SETTINGS_PRESET_DEFAULT,
    SETTINGS_PRESET_REFERENCE_PATH_TRACER,
    SETTINGS_PRESET_MIS_NEE_PATH_TRACER,
    SETTINGS_PRESET_RIS_NEE_PATH_TRACER,
    SETTINGS_PRESET_RESTIR_DI_FAST,
    SETTINGS_PRESET_RESTIR_DI_EFFICIENCY,
    SETTINGS_PRESET_RESTIR_GI,
    SETTINGS_PRESET_RESTIR_DI_GI
};

#endif
