/*
 * Copyright 2026 Tom Clabault. GNU GPL3 license.
 * GNU GPL3 license copy: https://www.gnu.org/licenses/gpl-3.0.txt
 */

#ifndef HOST_DEVICE_COMMON_ILLUMINATION_AWARE_KD_TREE_LEARNING_TO_CLUSTER_STATISTICS_UPDATE_MODE_H
#define HOST_DEVICE_COMMON_ILLUMINATION_AWARE_KD_TREE_LEARNING_TO_CLUSTER_STATISTICS_UPDATE_MODE_H

enum class IlluminationAwareKDTreeStatisticsUpdateMode : unsigned int
{
	UPDATE_ALL			  = 0u,
	INITIALIZE_EMPTY_ONLY = 1u
};

#endif // #ifndef HOST_DEVICE_COMMON_ILLUMINATION_AWARE_KD_TREE_LEARNING_TO_CLUSTER_STATISTICS_UPDATE_MODE_H
