/*
 * Copyright 2025 Tom Clabault. GNU GPL3 license.
 * GNU GPL3 license copy: https://www.gnu.org/licenses/gpl-3.0.txt
 */

#ifndef DEVICE_KERNELS_RESTIR_PG_SPLATTING_H
#define DEVICE_KERNELS_RESTIR_PG_SPLATTING_H

#include "Device/includes/FixIntellisense.h"
#include "Device/includes/ReSTIR/PG/SplattingSample.h"

#include "HostDeviceCommon/RenderData.h"

HIPRT_DEVICE float compute_sample_responsibility(ReSTIRPGDistribution& hash_grid_cell_distribution,
												 float3_t sample_direction,
												 int distribution_component,
												 const ReSTIRPGSettings& restir_pg_settings)
{
	VMFMixtureComponent& vmf_mixture_component = hash_grid_cell_distribution.distribution_components[distribution_component];

	float component_weight = vmf_mixture_component.weight;
	return component_weight * vmf_mixture_component.vmf.density_evaluation(sample_direction);
}

HIPRT_DEVICE void atomic_accumulate_sample(
	const ReSTIRPGSettings& restir_pg_settings, float3_t sample_direction, float responsibility, int distribution_component, unsigned int hash_grid_cell_index)
{
	const ReSTIRPGDistributionSufficientStatisticsSoADevice& sufficient_statistics = restir_pg_settings.hash_grid_distributions_sufficient_statistics_soa;

	unsigned int index = distribution_component * restir_pg_settings.hash_grid_total_number_of_cells + hash_grid_cell_index;
	hippt::atomic_fetch_add(&sufficient_statistics.directions_sum_x[index], sample_direction.x * responsibility);
	hippt::atomic_fetch_add(&sufficient_statistics.directions_sum_y[index], sample_direction.y * responsibility);
	hippt::atomic_fetch_add(&sufficient_statistics.directions_sum_z[index], sample_direction.z * responsibility);
	hippt::atomic_fetch_add(&sufficient_statistics.responsibility_weights_sum[index], responsibility);
	hippt::atomic_fetch_add(&sufficient_statistics.sample_count[hash_grid_cell_index], 1u);
}

#ifdef __KERNELCC__
GLOBAL_KERNEL_SIGNATURE(void) ReSTIR_PG_Splatting(HIPRTRenderData render_data)
#else
GLOBAL_KERNEL_SIGNATURE(void) inline ReSTIR_PG_Splatting(HIPRTRenderData render_data, int x, int y)
#endif
{
#ifdef __KERNELCC__
	const uint32_t x = blockIdx.x * blockDim.x + threadIdx.x;
	const uint32_t y = blockIdx.y * blockDim.y + threadIdx.y;
#endif

	if (x >= render_data.render_settings.render_resolution.x || y >= render_data.render_settings.render_resolution.y)
		return;

	uint32_t pixel_index				  = y * render_data.render_settings.render_resolution.x + x;
	uint32_t pixel_count				  = render_data.render_settings.render_resolution.x * render_data.render_settings.render_resolution.y;
	uint32_t restir_reservoir_pixel_index = render_data.render_settings.restir_gi_settings.restir_output_reservoirs[pixel_index].sample.pixel_index;
	if (restir_reservoir_pixel_index == static_cast<unsigned int>(-1))
		// That means potentially no spatial reuse / temporal so our reservoir didn't move
		restir_reservoir_pixel_index = pixel_index;

	const ReSTIRPGSettings& restir_pg_settings = render_data.render_settings.restir_pg_settings;
	// For each bouncen, splatting the sample of that bounce (for the current pixel) into the hash grid
	for (int bounce = 0; bounce < render_data.render_settings.nb_bounces; bounce++)
	{
		ReSTIRPGSplattingSample sample = restir_pg_settings.splatting_samples[restir_reservoir_pixel_index + bounce * pixel_count];
		if (!sample.valid_sample())
		{
			// If the sample at this bounce is not valid, then the samples for the next bounces are not valid either because they are generated by reconnecting
			// to
			// that sample, so we can just stop here
			break;
		}

		unsigned int checksum;
		unsigned int sample_hash_grid_index =
			restir_pg_settings.hash_position_data(sample.position, render_data.current_camera, checksum) % restir_pg_settings.hash_grid_total_number_of_cells;
		unsigned int sample_hash_grid_index_before = sample_hash_grid_index;

		if (!HashGrid::resolve_collision<ReSTIRPGHashGridCollisionResolveSteps, true>(
				restir_pg_settings.hash_grid_checksums, restir_pg_settings.hash_grid_total_number_of_cells, sample_hash_grid_index, checksum))
		{
			// If the collision resolution failed, then we just skip this sample and don't insert it into the hash grid
			if (sample_hash_grid_index < 10 && ReSTIRPGDistributionComponentCount == 2 && render_data.render_settings.sample_number == 0)
				printf("Collision not resolved, existing checksum: %u, hash grid index: %u, checksum: %u\n",
					   hippt::atomic_load(&restir_pg_settings.hash_grid_checksums[sample_hash_grid_index]), sample_hash_grid_index_before, checksum);

			continue;
		}

		if (ReSTIRPGDistributionComponentCount == 2 && sample_hash_grid_index < 10)
			printf("gone through\n");

		if (!hippt::atomic_compare_exchange(&restir_pg_settings.grid_cell_alive[sample_hash_grid_index], 0u, 1u))
		{
			// Setting the grid cell as alive
			unsigned int grid_cell_alive_index							   = hippt::atomic_fetch_add(restir_pg_settings.grid_cell_alive_count, 1u);
			restir_pg_settings.grid_cell_alive_list[grid_cell_alive_index] = sample_hash_grid_index;

			if (ReSTIRPGDistributionComponentCount == 2 && sample_hash_grid_index < 10)
				printf("+1\n");
		}

		/**
		 * Inserting the sample into the sufficient statistics of the hash grid cell, in each component for the expectation step of the EM algorithm
		 */
		ReSTIRPGDistribution& distribution = restir_pg_settings.hash_grid_distributions[sample_hash_grid_index];

		// Begin by computing the responsibility of this sample for each component of the distribution of the hash grid cell it maps to
		float sum_responsibilities = 0.0f;
		float responsibilities[ReSTIRPGDistributionComponentCount];
		for (int component = 0; component < ReSTIRPGDistributionComponentCount; component++)
		{
			float responsibility = compute_sample_responsibility(distribution, sample.incident_direction, component, restir_pg_settings);

			responsibilities[component] = responsibility;
			sum_responsibilities += responsibility;
		}

		// Normalize responsibilities
		for (int component = 0; component < ReSTIRPGDistributionComponentCount; component++)
			responsibilities[component] /= sum_responsibilities;

		for (int component = 0; component < ReSTIRPGDistributionComponentCount; component++)
		{
			float responsibility = responsibilities[component];

			atomic_accumulate_sample(restir_pg_settings, sample.incident_direction, responsibility, component, sample_hash_grid_index);
		}
	}
}

#endif // DEVICE_KERNELS_RESTIR_PG_SPLATTING_H
